'use client';
import {useEffect,useState} from 'react';
import CustomerAccount from '../shop/customer-account';
import LineContact from '../shop/line-contact';
import InstallApp from '../install-app';
import PromotionCard from '../shop/promotion-card';
import {PriceAndBooking,RentalPolicies} from './shop-policy';
import type {ShopInfo} from '@/lib/shop';
type Rental={id:string;item:string;start:string;end:string;status:string;online:boolean;deposit:number;fee:number;fine:number;damage:number};
type Account={memberId:string;name:string;phone:string;balance:number;rentals:Rental[]};
type Review={id:string;name:string;text:string;image:string};
const menus=[['home','หน้าแรก'],['prices','ราคาเช่าชุด'],['deposit','เงินประกัน'],['rules','กฎระเบียบการเช่า'],['promotions','โปรโมชั่น'],['sizes','ตารางไซซ์'],['rentals','ตรวจสอบรายการเช่า'],['reviews','รีวิวร้าน']];
const baht=(value:number)=>value.toLocaleString('th-TH')+' บาท';
const prices=[150,250,350];
export default function MemberHome({info,reviews}:{info:ShopInfo;reviews:Review[]}){
  const [data,setData]=useState<Account|null>(null),[error,setError]=useState(''),[copied,setCopied]=useState(false),[view,setView]=useState('home');
  const [rentalId,setRentalId]=useState(''),[text,setText]=useState(''),[consent,setConsent]=useState(false),[sending,setSending]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{let active=true;async function load(){try{const r=await fetch('/api/shop/customer-account',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();if(active){setData(d);setError('');}}catch{if(active)setError('โหลดข้อมูลไม่สำเร็จ กรุณาลองใหม่');}}void load();const timer=setInterval(load,60000);window.addEventListener('focus',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',load);};},[]);
  async function review(e:React.FormEvent){e.preventDefault();setSending(true);setError('');setMessage('');try{const r=await fetch('/api/shop/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rentalId,text,consent})});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage('ขอบคุณค่ะ รีวิวจะเผยแพร่หลังร้านตรวจสอบ');setText('');setConsent(false);}catch(e){setError(e instanceof Error?e.message:'ส่งรีวิวไม่สำเร็จ');}finally{setSending(false);}}
  const returned=data?.rentals.filter(r=>r.status==='คืนแล้ว')||[];
  const promotions=<PromotionCard info={info}/>;
  return <div className="min-h-screen bg-[#fcfaf6] text-stone-800"><header className="border-b bg-[#fcfaf6] sticky top-0 z-30"><div className="max-w-4xl mx-auto p-4 flex items-center justify-between gap-3"><a href="/member" className="flex items-center gap-2"><img src="/logo.png" alt="HONEY STUDIO" width={40} height={40}/><strong className="font-serif tracking-widest text-sm">HONEY STUDIO</strong></a><div className="flex items-center gap-2"><CustomerAccount/><button className="text-xs underline" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.href='/join';}}>ออกจากระบบ</button></div></div><nav aria-label="เมนูสมาชิกหน้าร้าน" className="max-w-4xl mx-auto flex overflow-x-auto px-4 pb-3 gap-4">{menus.map(([id,label])=><button key={id} onClick={()=>{setView(id);setError('');setMessage('');}} className={'whitespace-nowrap text-xs py-2 border-b '+(view===id?'text-amber-800 border-amber-700':'text-stone-500 border-transparent')}>{label}</button>)}</nav></header><main className="max-w-4xl mx-auto px-5 py-7 pb-40 space-y-5"><h1 className="shop-title">{menus.find(([id])=>id===view)?.[1]}</h1>{error&&<p role="alert" className="text-red-600 text-sm">{error}</p>}{message&&<p role="status" className="text-green-700 text-sm">{message}</p>}
    {view==='home'&&<><section className="shop-panel text-center"><img src="/logo.png" alt="โลโก้ร้าน" width={110} height={110} className="mx-auto"/><h2 className="font-serif text-2xl tracking-widest mt-3">HONEY STUDIO</h2><p className="whitespace-pre-line leading-7 mt-4">{info.intro}</p>{data&&<p className="mt-4">ยินดีต้อนรับค่ะ {data.name}</p>}</section>{data&&<section className="shop-panel"><div className="flex justify-between items-center"><h2 className="font-semibold">สมาชิกของฉัน</h2><strong className="text-amber-800">{data.balance} แต้ม</strong></div>{data.phone&&<p className="mt-3">เบอร์สมาชิก {data.phone}</p>}<p className="text-xs text-stone-500 mt-2">เช่าและคืนครบ 1 ครั้ง = 1 แต้ม · ดูการแจ้งเตือนที่กระดิ่ง</p><details className="mt-4 text-sm"><summary>แสดงรหัสสมาชิกให้พนักงาน</summary><p className="font-mono break-all bg-stone-100 rounded-lg p-3 mt-3">{data.memberId}</p><button className="shop-button secondary mt-3" onClick={async()=>{try{await navigator.clipboard.writeText(data.memberId);setCopied(true);}catch{setError('กรุณาเลือกรหัสสมาชิกแล้วคัดลอก');}}}>{copied?'คัดลอกแล้ว':'คัดลอกรหัสสมาชิก'}</button></details><button className="shop-button mt-4" onClick={()=>setView('rentals')}>ตรวจสอบรายการเช่า</button></section>}{promotions}<InstallApp/></>}
    {view==='prices'&&<PriceAndBooking info={info}/>}
    {view==='deposit'&&<><div className="grid sm:grid-cols-3 gap-4">{prices.map(price=><section key={price} className="shop-panel"><p className="text-sm">ชุดราคาเช่า 1 วัน {baht(price)}</p><p className="font-bold text-lg mt-3">เงินประกัน {baht(price)}</p></section>)}</div><section className="shop-panel"><h2 className="font-semibold mb-3">เงื่อนไขคืนเงินประกัน</h2><p className="whitespace-pre-line leading-7">{info.depositTerms}</p><p className="text-xs text-stone-500 mt-4">ยอดเงินประกันของชุดที่เช่าจริงแสดงใน “ตรวจสอบรายการเช่า”</p></section></>}
    {view==='rules'&&<RentalPolicies info={info}/>}
    {view==='promotions'&&promotions}
    {view==='sizes'&&<><section className="shop-panel"><h2 className="font-semibold mb-3">วิธีวัดขนาดรอบตัว</h2><p className="text-sm leading-7">ใช้สายวัดแนบพอดี ไม่ดึงรัด ยืนตามปกติ และให้สายวัดขนานกับพื้น วัดเป็นนิ้วเพื่อเทียบกับขนาดชุดของร้าน</p></section>{[['รอบอก','พันสายวัดผ่านส่วนที่กว้างที่สุดของอกและรอบหลัง'],['รอบเอว','วัดรอบส่วนที่คอดที่สุดของเอว ไม่แขม่วท้อง'],['รอบสะโพก','วัดรอบส่วนที่กว้างที่สุดของสะโพกและก้น']].map(([label,description])=><section key={label} className="shop-panel"><h2 className="font-semibold">{label}</h2><p className="text-sm leading-7 mt-2">{description}</p></section>)}<p className="text-xs text-stone-500">ขนาดที่วัดรอบตัวใช้ตัวเลขตามสายวัดได้เลย ให้พนักงานช่วยเทียบความพอดีก่อนเช่า</p></>}
    {view==='rentals'&&(!data?<p>กำลังโหลดรายการเช่า…</p>:data.rentals.length===0?<p className="shop-panel">ยังไม่มีรายการเช่า ให้พนักงานผูกเบอร์หรือรหัสสมาชิกกับรายการเช่าของคุณค่ะ</p>:data.rentals.map(r=><article className="shop-panel" key={r.id}><div className="flex justify-between gap-3"><h2 className="font-semibold">{r.item}</h2><span className="text-xs text-amber-800">{r.status}</span></div><p className="text-sm mt-3">วันรับ {r.start} · กำหนดคืน {r.end}</p><p className="text-sm mt-2">ค่าเช่า {baht(r.fee)} · เงินประกัน {baht(r.deposit)}</p>{(r.fine>0||r.damage>0)&&<p className="text-sm mt-2">ค่าปรับ {baht(r.fine)} · ค่าเสียหาย {baht(r.damage)}</p>}</article>))}
    {view==='reviews'&&<><section className="space-y-4">{reviews.length===0?<p className="shop-panel">ยังไม่มีรีวิวที่ร้านอนุมัติให้เผยแพร่</p>:reviews.map(r=><article key={r.id} className="shop-panel"><h2 className="font-semibold">{r.name}</h2><p className="whitespace-pre-line text-sm leading-7 mt-3">{r.text}</p>{r.image&&<img src={r.image} alt="ภาพรีวิวที่ลูกค้าอนุญาตให้เผยแพร่" className="max-w-56 rounded-xl mt-3"/>}</article>)}</section>{returned.length>0&&<form className="shop-panel space-y-4" onSubmit={review}><h2 className="font-semibold">เขียนรีวิวหลังใช้บริการ</h2><label className="shop-field">รายการที่คืนแล้ว<select required value={rentalId} onChange={e=>setRentalId(e.target.value)}><option value="">เลือกรายการเช่า</option>{returned.map(r=><option key={r.id} value={r.id}>{r.item} · {r.end}</option>)}</select></label><label className="shop-field">รีวิวของคุณ<textarea required maxLength={2000} value={text} onChange={e=>setText(e.target.value)}/></label><label className="flex gap-2 text-sm"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>อนุญาตให้ร้านเผยแพร่ชื่อและข้อความรีวิวนี้</label><button disabled={sending} className="shop-button">{sending?'กำลังส่ง…':'ส่งรีวิวให้ร้านตรวจสอบ'}</button></form>}</>}
  </main><LineContact/></div>;
}
