'use client';
import {useEffect,useState} from 'react';
import CustomerAccount from '../shop/customer-account';
import LineContact from '../shop/line-contact';
import InstallApp from '../install-app';
type Account={memberId:string;name:string;balance:number;rentals:{id:string;item:string;start:string;end:string;status:string;online:boolean}[]};
export default function MemberHome(){
  const [data,setData]=useState<Account|null>(null),[error,setError]=useState(''),[copied,setCopied]=useState(false);
  useEffect(()=>{let active=true;async function load(){try{const r=await fetch('/api/shop/customer-account',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();if(active){setData(d);setError('');}}catch{if(active)setError('โหลดข้อมูลไม่สำเร็จ กรุณาลองใหม่');}}void load();const timer=setInterval(load,60000);window.addEventListener('focus',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',load);};},[]);
  return <div className="min-h-screen bg-[#fcfaf6] text-stone-800"><header className="max-w-3xl mx-auto p-5 flex items-center justify-between"><a href="/member" className="font-serif font-bold tracking-widest">HONEY STUDIO</a><div className="flex items-center gap-3"><CustomerAccount/><button className="text-xs underline" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.href='/join';}}>ออกจากระบบ</button></div></header><main className="max-w-3xl mx-auto px-5 pb-40 space-y-5"><h1 className="shop-title">สมาชิกหน้าร้าน</h1>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>กำลังโหลดข้อมูลสมาชิก…</p>}{data&&<><section className="shop-panel"><h2 className="font-bold text-lg">สวัสดีค่ะ {data.name}</h2><p className="text-sm my-3">แสดงรหัสสมาชิกนี้ให้พนักงานผูกกับรายการเช่าของคุณ</p><p className="font-mono break-all bg-stone-100 rounded-lg p-3">{data.memberId}</p><button className="shop-button secondary mt-3" onClick={async()=>{try{await navigator.clipboard.writeText(data.memberId);setCopied(true);}catch{setError('กรุณาเลือกรหัสสมาชิกแล้วคัดลอก');}}}>{copied?'คัดลอกแล้ว':'คัดลอกรหัสสมาชิก'}</button><p className="mt-4 font-semibold text-amber-800">แต้มสะสม {data.balance} แต้ม</p><p className="text-xs text-stone-500 mt-1">เช่าและคืนครบ 1 ครั้ง = 1 แต้ม · ดูประวัติและแจ้งเตือนที่กระดิ่ง</p></section><section><h2 className="font-bold mb-3">รายการเช่าของฉัน</h2>{data.rentals.length===0?<p className="shop-panel text-sm">ยังไม่มีรายการเช่า เมื่อพนักงานผูกบัญชีแล้ว รายการและกำหนดคืนจะแสดงที่นี่ค่ะ</p>:data.rentals.map(r=><article className="shop-panel mb-3" key={r.id}><h3 className="font-semibold">{r.item}</h3><p className="text-sm mt-2">รับชุด {r.start} · คืนชุด {r.end}</p><p className="text-sm mt-1">สถานะ: {r.status}</p></article>)}</section></>}<InstallApp/><a href="/shop" className="block underline text-sm">ดูชุดของร้าน</a></main><LineContact/></div>;
}
