"use client";
import {useEffect,useState} from 'react';
import type {ShopInfo} from '@/lib/shop';
type Booking={id:string;item:string;cust:string;phone:string;start:string;end:string;fee:number;deposit:number;status:string;paymentStatus:string;paymentSlip:string;stockApplied:boolean;stockReturned:boolean};
type Review={id:string;name:string;text:string;image:string;consent:boolean;approved:boolean};
const labels:Record<keyof ShopInfo,string>={intro:'แนะนำร้าน',phone:'เบอร์โทร',line:'LINE ID (เช่น @honeystudio)',map:'ลิงก์แผนที่ https://',address:'ที่อยู่ร้าน',social:'ลิงก์โซเชียล https://',bank:'ธนาคาร / พร้อมเพย์',accountName:'ชื่อบัญชี',account:'เลขบัญชี / พร้อมเพย์',promotions:'โปรโมชั่น (หนึ่งรายการต่อบรรทัด)',depositTerms:'เงื่อนไขเงินประกันและคืนเงิน',rentalRules:'กฎระเบียบการเช่า / คืนช้า / เสียหาย',promotionTerms:'เงื่อนไขใช้โปรโมชั่น',bookingGuide:'ขั้นตอนจอง / เงินจอง',rentalCounting:'การนับวันเช่า',collectionTerms:'รับชุด / ส่งคืน / ค่าจัดส่ง',damageTerms:'ค่าเสียหาย / อุปกรณ์สูญหาย',changeTerms:'เลื่อน / เปลี่ยน / ยกเลิก',purchaseTerms:'ซื้อชุด',outstandingTerms:'ไม่คืนชุด / ยอดค้าง',promotionStart:'วันเริ่มโปรโมชั่น',promotionEnd:'วันสิ้นสุดโปรโมชั่น'};
export default function ShopManagement({role}:{role:string}){
  const [bookings,setBookings]=useState<Booking[]>([]),[reviews,setReviews]=useState<Review[]>([]),[settings,setSettings]=useState<ShopInfo|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const manageSettings=['เจ้าของ','ผู้ดูแลระบบ'].includes(role);
  async function request(url:string,method='GET',body?:object){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'บันทึกไม่สำเร็จ');return d;}
  async function load(){const [b,r,s]=await Promise.all([request('/api/shop/bookings'),request('/api/shop/reviews?manage=1'),request('/api/shop/settings')]);setBookings(b);setReviews(r);setSettings(s);}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function act(url:string,method:string,body:object){setBusy(true);setError('');setMessage('');try{await request(url,method,body);await load();setMessage('บันทึกแล้ว');}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}}
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><h1 className="text-2xl font-bold">หน้าลูกค้า / จองออนไลน์</h1><a href="/shop" target="_blank" rel="noreferrer" className="underline">เปิดหน้าแอพลูกค้า</a></div>{error&&<p role="alert" className="text-red-700 bg-red-50 p-3 rounded-lg">{error}</p>}{message&&<p role="status" className="text-green-700">{message}</p>}
    <section className="space-y-3"><h2 className="font-bold">การจองออนไลน์ ({bookings.length})</h2>{!bookings.length&&<p>ยังไม่มีการจองออนไลน์</p>}{bookings.map(b=><article key={b.id} className="shop-panel"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{b.item}</h3><span>{b.status} · {b.paymentStatus}</span></div><p className="text-sm mt-2">{b.cust} · {b.phone} · วันรับ {b.start} · คืน {b.end}</p><p className="text-sm">ค่าเช่า {b.fee.toLocaleString('th-TH')} · มัดจำ {b.deposit.toLocaleString('th-TH')} · รวม {(b.fee+b.deposit).toLocaleString('th-TH')} บาท</p><div className="flex flex-wrap gap-3 mt-4">{b.paymentSlip&&<a className="underline" href={b.paymentSlip} target="_blank" rel="noreferrer">ดูหลักฐานชำระ</a>}{b.paymentSlip&&b.paymentStatus!=='ชำระแล้ว'&&!['ยกเลิก','คืนแล้ว'].includes(b.status)&&<button disabled={busy} className="shop-button secondary" onClick={()=>act('/api/shop/bookings/'+b.id,'PATCH',{action:'paid'})}>ตรวจแล้ว / ยืนยันชำระ</button>}{b.paymentStatus==='ชำระแล้ว'&&!b.stockApplied&&!['ยกเลิก','คืนแล้ว'].includes(b.status)&&<button disabled={busy} className="shop-button" onClick={()=>act('/api/rentals/'+b.id,'PATCH',{status:'รับชุดแล้ว'})}>ส่งชุดให้ลูกค้า</button>}{b.stockApplied&&!b.stockReturned&&<button disabled={busy} className="shop-button secondary" onClick={()=>act('/api/rentals/'+b.id,'PATCH',{status:'คืนแล้ว'})}>รับคืนชุด</button>}{!b.stockApplied&&!['ยกเลิก','คืนแล้ว'].includes(b.status)&&<button disabled={busy} className="text-sm underline text-red-700" onClick={()=>{if(window.confirm('ยืนยันยกเลิกการจองนี้?'))act('/api/shop/bookings/'+b.id,'PATCH',{action:'cancel'});}}>ยกเลิก</button>}</div></article>)}</section>
    <section className="shop-panel space-y-4"><h2 className="font-bold">รีวิวที่ลูกค้าอนุญาตให้เผยแพร่</h2>{!reviews.length&&<p>ยังไม่มีรีวิวให้ตรวจสอบ</p>}{reviews.map(r=><article key={r.id} className="border-t pt-4"><h3 className="font-semibold">{r.name}</h3><p className="whitespace-pre-line my-3">{r.text}</p>{r.image&&<img src={r.image} alt="ภาพรีวิวที่ลูกค้าอนุญาต" className="w-24 rounded-lg mb-3"/>}<button disabled={busy||!r.consent} className="shop-button secondary" onClick={()=>act('/api/shop/reviews','PATCH',{id:r.id,approved:!r.approved})}>{r.approved?'ซ่อนรีวิว':'ตรวจแล้ว / เผยแพร่รีวิว'}</button></article>)}</section>
    {manageSettings&&settings&&<form className="shop-panel space-y-4" onSubmit={e=>{e.preventDefault();act('/api/shop/settings','PUT',settings);}}><h2 className="font-bold">ข้อมูลร้าน / โปรโมชั่น / บัญชีรับชำระ</h2><div className="grid md:grid-cols-2 gap-4">{(Object.keys(labels) as (keyof ShopInfo)[]).map(key=><label key={key} className="shop-field">{labels[key]}{!['phone','line','map','social','bank','accountName','account','promotionStart','promotionEnd'].includes(key)?<textarea value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})}/>:<input type={key==='promotionStart'||key==='promotionEnd'?'date':'text'} value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})}/>}</label>)}</div><button disabled={busy} className="shop-button">บันทึกข้อมูลหน้าลูกค้า</button></form>}
  </div>;
}
