'use client';
import {useEffect,useState} from 'react';
import {Bell,X,Star} from 'lucide-react';
type Notice={id:string;title:string;body:string;href:string;read:boolean};
type Account={balance:number;history:{id:string;points:number;createdAt:string}[];notifications:Notice[]};
export default function CustomerAccount(){
  const [data,setData]=useState<Account|null>(null),[open,setOpen]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let active=true;async function refresh(){try{const r=await fetch('/api/shop/customer-account',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();if(active){setData(d);setError('');}}catch{if(active)setError('โหลดการแจ้งเตือนไม่สำเร็จ');}}void refresh();const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);};},[]);
  async function markRead(ids:string[]){try{const r=await fetch('/api/shop/customer-account',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});if(!r.ok)throw new Error();setData(d=>d?{...d,notifications:d.notifications.map(n=>ids.includes(n.id)?{...n,read:true}:n)}:d);}catch{setError('บันทึกการอ่านไม่สำเร็จ');}}
  const unread=data?.notifications.filter(n=>!n.read).length||0;
  return <div className="relative"><button aria-label={'แจ้งเตือนและแต้มสะสม'+(unread?' '+unread+' รายการใหม่':'')} aria-expanded={open} onClick={()=>setOpen(!open)} className="relative p-2"><Bell size={22}/>{unread>0&&<span className="absolute -top-1 -right-1 rounded-full bg-red-600 text-white text-[10px] px-1.5">{unread}</span>}</button>{open&&<section aria-label="แจ้งเตือนและแต้มสะสม" className="fixed sm:absolute top-24 sm:top-12 right-3 sm:right-0 w-[min(360px,calc(100vw-24px))] max-h-[70vh] overflow-auto bg-white border border-stone-200 shadow-xl rounded-2xl p-4 z-50"><div className="flex justify-between items-center"><h2 className="font-semibold">แจ้งเตือนของฉัน</h2><button aria-label="ปิดการแจ้งเตือน" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="bg-amber-50 rounded-xl p-4 my-3"><p className="flex items-center gap-2"><Star size={18}/><strong>{data?.balance??'…'} แต้มสะสม</strong></p><p className="text-xs text-stone-600 mt-2">เช่าและคืนครบ 1 ครั้ง = 1 แต้ม</p><p className="text-xs text-stone-500">ให้แต้มหลังคืนชุดของบัญชีนี้เรียบร้อย</p>{data&&data.history.length>0&&<details className="mt-2 text-xs"><summary>ประวัติแต้ม</summary>{data.history.map(e=><p key={e.id} className="mt-2">{new Date(e.createdAt).toLocaleDateString('th-TH')} · {e.points>0?'+':''}{e.points} แต้ม</p>)}</details>}</div>{error&&<p role="alert" className="text-red-600 text-xs">{error}</p>}{!data&&!error&&<p>กำลังโหลด…</p>}{data&&<><button className="underline text-xs mb-3" onClick={()=>void markRead(data.notifications.filter(n=>!n.read).map(n=>n.id))}>อ่านทั้งหมด</button>{data.notifications.length===0&&<p className="text-stone-500 text-sm">ยังไม่มีการแจ้งเตือน</p>}{data.notifications.map(n=><div key={n.id} className={'border-t py-3 '+(!n.read?'bg-amber-50':'')}><a href={n.href} onClick={()=>void markRead([n.id])}><strong className="text-sm">{n.title}</strong><p className="text-xs text-stone-500 mt-1">{n.body}</p></a>{!n.read&&<button className="text-xs underline mt-2" onClick={()=>void markRead([n.id])}>ทำเครื่องหมายว่าอ่านแล้ว</button>}</div>)}</>}</section>}</div>;
}
