"use client";
import {useEffect,useState} from 'react';
import {Shirt,ArrowRight,CalendarDays,Menu,X,CheckCircle2,MapPin,Phone,MessageCircle} from 'lucide-react';
import InstallApp from '../install-app';
import CustomerAccount from './customer-account';
import LineContact from './line-contact';
import PromotionCard from './promotion-card';
import LoyaltyCard from './loyalty-card';
import MemberLoginForm from './member-login-form';
import AvailabilityCalendar from './availability-calendar';
import {rentalPrice} from '@/lib/product-details';
import {bookingDays,thaiToday} from '@/lib/booking-availability';
import type {ShopInfo} from '@/lib/shop';
type Product={id:string;name:string;cat:string;color:string;size:string;image:string;imageBack:string;rent:number;rentPrices:string;specs:[string,string][];status:string;available:boolean;prices:{days:number;price:number}[]};
type Booking={online:boolean;rewardUsed:boolean;id:string;code:string;item:string;cust:string;phone:string;start:string;end:string;fee:number;deposit:number;status:string;paymentStatus:string;paymentSlip:string;stockApplied:boolean;stockReturned:boolean};
type Review={id:string;name:string;text:string;image:string};
const menus=[['login','เข้าสู่ระบบลูกค้า'],['bookings','ข้อมูลการจอง+สะสมแต้ม'],['details','รายละเอียดชุด'],['calendar','ปฏิทินจองชุด'],['payment','ชำระเงิน'],['reviews','รีวิวลูกค้า'],['contact','ติดต่อร้าน']];
const money=(n:number)=>n.toLocaleString('th-TH')+' บาท';
export default function CustomerShop({info,products,reviews,popularIds,user,initialView,initialProduct,initialBooking}:{info:ShopInfo;products:Product[];reviews:Review[];popularIds:string[];user:{name:string;staff:boolean}|null;initialView:string;initialProduct:string;initialBooking:string}){
  const [view,setView]=useState([...menus.map(([id])=>id),'booking'].includes(initialView)?initialView:(user?'bookings':'login')),[menuOpen,setMenuOpen]=useState(false),[productId,setProductId]=useState(initialProduct||products[0]?.id||''),[bookingId,setBookingId]=useState(initialBooking);
  const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[color,setColor]=useState(''),[size,setSize]=useState(''),[maxPrice,setMaxPrice]=useState(''),[limit,setLimit]=useState(24);
  const [start,setStart]=useState(thaiToday),[end,setEnd]=useState(()=>new Date(Date.parse(thaiToday())+86400000).toISOString().slice(0,10)),[month,setMonth]=useState(()=>thaiToday().slice(0,7));
  const [calendar,setCalendar]=useState<{date:string;remaining:number}[]>([]),[remaining,setRemaining]=useState<number|null>(null),[calendarBusy,setCalendarBusy]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [cust,setCust]=useState(user?.name||''),[phone,setPhone]=useState(''),[bookings,setBookings]=useState<Booking[]>([]),[loadingBookings,setLoadingBookings]=useState(false);
  const [reviewText,setReviewText]=useState(''),[consent,setConsent]=useState(false),[reviewImage,setReviewImage]=useState('');
  const product=products.find(p=>p.id===productId),booking=bookings.find(b=>b.id===bookingId);
  let days=0;try{days=bookingDays(start,end);}catch{}
  const fee=product&&days?rentalPrice(product,days):0;
  const popular=[...popularIds.map(id=>products.find(p=>p.id===id)).filter((p):p is Product=>!!p),...products.filter(p=>p.image&&!popularIds.includes(p.id))].slice(0,6);
  const featured=popular.length?popular:products.slice(0,6);
  function go(next:string,id=productId,booking=bookingId){setView(next);setProductId(id);setBookingId(booking);setMenuOpen(false);setError('');setMessage('');window.history.replaceState(null,'','/shop?'+new URLSearchParams({view:next,...(id?{product:id}:{}),...(booking?{booking}:{})}));window.scrollTo({top:0,behavior:'smooth'});}
  async function json(url:string,options?:RequestInit){const r=await fetch(url,{cache:'no-store',...options});const data=await r.json();if(!r.ok)throw new Error(data.error||'ทำรายการไม่สำเร็จ');return data;}
  async function loadBookings(){if(!user)return;setLoadingBookings(true);try{const result=await json('/api/shop/bookings');setBookings(result);if(!bookingId&&result.length)setBookingId(result[0].id);}catch(e){setError(e instanceof Error?e.message:'โหลดไม่สำเร็จ');}finally{setLoadingBookings(false);}}
  useEffect(()=>{if(['payment','bookings','reviews'].includes(view)&&user)loadBookings();},[view]);
  useEffect(()=>{
    if(!productId||!['calendar','booking'].includes(view))return;
    let alive=true;setCalendarBusy(true);setCalendar([]);
    json(`/api/shop/products/${encodeURIComponent(productId)}/availability?month=${month}`).then(data=>{if(alive)setCalendar(data.days);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setCalendarBusy(false);});return()=>{alive=false;};
  },[productId,month,view]);
  useEffect(()=>{
    if(!productId||view!=='booking'||!days){setRemaining(null);return;}
    let alive=true;setRemaining(null);
    json(`/api/shop/products/${encodeURIComponent(productId)}/availability?start=${start}&end=${end}`).then(data=>{if(alive)setRemaining(data.remaining);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};
  },[productId,start,end,view,days]);
  async function book(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await json('/api/shop/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:productId,cust,phone,start,end})});setBookings(prev=>[result,...prev]);go('payment',productId,result.id);setMessage('บันทึกการจองแล้ว กรุณาชำระและส่งหลักฐานให้ร้านตรวจสอบ');}catch(e){setError(e instanceof Error?e.message:'จองไม่สำเร็จ');}finally{setBusy(false);}}
  async function upload(file:File,kind:string){if(!bookingId)throw new Error('เลือกการจองก่อน');const form=new FormData();form.set('file',file);form.set('rentalId',bookingId);form.set('kind',kind);return json('/api/shop/upload',{method:'POST',body:form});}
  async function sendFile(file:File,kind:string){setBusy(true);setError('');try{const data=await upload(file,kind);if(kind==='review')setReviewImage(data.url);else{await loadBookings();setMessage('ส่งหลักฐานแล้ว รอร้านตรวจสอบ');}}catch(e){setError(e instanceof Error?e.message:'อัปโหลดไม่สำเร็จ');}finally{setBusy(false);}}
  async function cancel(b:Booking){if(!window.confirm('ยืนยันยกเลิกการจองนี้?'))return;setBusy(true);try{await json('/api/shop/bookings/'+encodeURIComponent(b.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel'})});await loadBookings();}catch(e){setError(e instanceof Error?e.message:'ยกเลิกไม่สำเร็จ');}finally{setBusy(false);}}
  async function sendReview(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await json('/api/shop/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rentalId:bookingId,text:reviewText,image:reviewImage,consent})});setMessage('ขอบคุณค่ะ รีวิวจะเผยแพร่หลังร้านตรวจสอบ');setReviewText('');setReviewImage('');setConsent(false);}catch(e){setError(e instanceof Error?e.message:'ส่งรีวิวไม่สำเร็จ');}finally{setBusy(false);}}
  const login=<div className="shop-panel text-center py-10"><h2 className="text-xl font-semibold">เข้าสู่ระบบเพื่อดูรายการของคุณ</h2><p className="mt-2 mb-5 text-stone-500">สมัครสมาชิกและจองชุดสำหรับวันสำคัญได้</p><a className="shop-button" href="/customer-login">เข้าสู่ระบบ / สมัครสมาชิก</a></div>;
  const chooseProduct=<label className="shop-field">เลือกชุด<select value={productId} onChange={e=>{setProductId(e.target.value);setError('');}}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>;
  const card=(p:Product)=><button key={p.id} className="shop-card text-left" onClick={()=>go('details',p.id)}>{p.image?<img loading="lazy" src={p.image} alt={p.name} className="aspect-[3/4] w-full object-cover"/>:<div className="aspect-[3/4] flex items-center justify-center bg-[#efe8df]"><Shirt size={46} strokeWidth={1} className="text-stone-400"/></div>}<div className="p-4"><p className="text-xs text-stone-500 mb-2">{p.cat} · {p.color||'ดูรายละเอียดสี'}</p><h3 className="font-semibold text-sm line-clamp-2 min-h-10">{p.name}</h3><div className="flex items-center justify-between mt-3 gap-2"><span className="text-sm">{p.rent>0?'เริ่ม '+money(p.rent):'สอบถามราคา'}</span><ArrowRight size={16}/></div></div></button>;
  const filtered=products.filter(p=>(p.name+' '+p.id).toLowerCase().includes(query.toLowerCase())&&(!category||p.cat===category)&&(!color||p.color===color)&&(!size||(size==='ไม่ระบุ'?!p.size:p.size===size))&&(!maxPrice||p.rent<=Number(maxPrice)));
  return <div className="customer-shop min-h-screen text-[#342d28] bg-[#fcfaf6]">
    <header className="sticky top-0 z-30 bg-[#fcfaf6]/95 backdrop-blur border-b border-stone-200"><div className="max-w-6xl mx-auto px-5 py-4 flex items-center justify-between gap-4"><a href="/" className="flex items-center gap-2"><img src="/logo.png" alt="HONEY STUDIO" width={45} height={45}/><div><strong className="font-serif tracking-[.18em] text-sm">HONEY STUDIO</strong><span className="block text-[10px] tracking-widest text-stone-500">DRESS RENTAL</span></div></a><div className="flex gap-4 items-center text-sm">{user?<><CustomerAccount/><span className="hidden sm:block">{user.name}</span>{user.staff&&<a href="/staff" className="underline">จัดการร้าน</a>}<button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.href='/shop';}}>ออกจากระบบ</button></>:<a href="/customer-login">เข้าสู่ระบบ</a>}<button aria-label="เมนู" onClick={()=>setMenuOpen(!menuOpen)} className="lg:hidden">{menuOpen?<X/>:<Menu/>}</button></div></div><nav aria-label="เมนูลูกค้า" className={(menuOpen?'flex':'hidden')+' lg:flex flex-wrap gap-x-5 gap-y-2 justify-center px-5 pb-4 text-xs'}>{menus.map(([id,label])=><button key={id} onClick={()=>go(id)} className={'py-1 border-b '+(view===id?'border-[#9c7741] text-[#805c2e]':'border-transparent text-stone-500')}>{label}</button>)}</nav></header>
    <main className="max-w-6xl mx-auto px-5 py-8 sm:py-12">
      {error&&<div role="alert" className="mb-5 rounded-xl p-4 bg-red-50 text-red-700">{error}</div>}{message&&<div role="status" className="mb-5 rounded-xl p-4 bg-green-50 text-green-800">{message}</div>}
      {view==='login'&&(!user?<MemberLoginForm/>:<section className="shop-panel"><h1 className="shop-title">เข้าสู่ระบบลูกค้า</h1><p>คุณเข้าสู่ระบบแล้ว: {user.name}</p><button className="shop-button mt-4" onClick={()=>go('bookings')}>ข้อมูลการจอง+สะสมแต้ม</button></section>)}

      {view==='details'&&<><h1 className="shop-title">รายละเอียดชุด</h1>{chooseProduct}{product&&<div className="grid md:grid-cols-2 gap-7 mt-6"><div className="grid grid-cols-2 gap-3">{[product.image,product.imageBack].filter(Boolean).map((image,i)=><img key={image} src={image} alt={product.name+(i?' ด้านหลัง':' ด้านหน้า')} className="w-full rounded-xl object-cover"/>)}{!product.image&&!product.imageBack&&<div className="shop-panel col-span-2 flex items-center justify-center h-80"><Shirt size={80} strokeWidth={1}/></div>}</div><div><p className="text-xs text-stone-500">{product.cat} · {product.color} · {product.id}</p><h2 className="text-2xl font-semibold mt-3">{product.name}</h2><div className="grid grid-cols-2 gap-3 my-6">{product.specs.map(([label,value])=><div className="shop-panel p-3" key={label}><div className="text-xs text-stone-500">{label}</div><strong>{value}</strong></div>)}</div><div className="shop-panel"><h3 className="font-semibold mb-3">ราคาเช่า</h3>{product.prices.map(p=><p key={p.days} className="flex justify-between py-1"><span>{p.days} วัน</span><span>{product.rent>0?money(p.price):'สอบถามร้าน'}</span></p>)}<p className="border-t mt-2 pt-2">เงินประกัน {product.rent>0?money(product.rent):'สอบถามร้าน'} · เพิ่มวันละ 50 บาท</p></div><div className="flex flex-wrap gap-3 mt-5"><button className="shop-button" onClick={()=>go('booking')}>จองชุดนี้</button><button className="shop-button secondary" onClick={()=>go('calendar')}>ตรวจวันว่าง</button><a className="text-sm underline self-center" href={'/p/'+encodeURIComponent(product.id)}>ดูรูปและตำหนิ</a></div></div></div>}</>}
      {(view==='calendar'||view==='booking')&&<><h1 className="shop-title">{view==='calendar'?'ปฏิทินจองชุด':'จองชุดออนไลน์'}</h1>{chooseProduct}<div className="grid md:grid-cols-2 gap-6 mt-6"><section className="shop-panel"><label className="shop-field">เดือน<input type="month" min={thaiToday().slice(0,7)} value={month} onChange={e=>setMonth(e.target.value)}/></label><p className="text-xs text-stone-500 my-4">สีเขียว: ว่าง · สีชมพู: เต็ม / ไม่พร้อมเช่า · วันคืนสามารถเริ่มการจองใหม่ได้</p>{calendarBusy?<p>กำลังตรวจวันว่าง…</p>:<AvailabilityCalendar days={calendar} onSelect={date=>{setStart(date);setEnd(new Date(Date.parse(date)+86400000).toISOString().slice(0,10));if(view==='calendar')go('booking');}}/>}</section>{view==='booking'?user?<form className="shop-panel space-y-4" onSubmit={book}><h2 className="font-semibold">วันรับ–คืนและข้อมูลลูกค้า</h2><label className="shop-field">วันรับ<input type="date" required min={thaiToday()} value={start} onChange={e=>setStart(e.target.value)}/></label><label className="shop-field">วันคืน<input type="date" required min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="shop-field">ชื่อลูกค้า<input required maxLength={200} value={cust} onChange={e=>setCust(e.target.value)}/></label><label className="shop-field">เบอร์โทร<input type="tel" required maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)}/></label><div className="bg-[#f5f1e8] p-4 rounded-xl"><p>{days?`${days} วัน`:'กรุณาเลือกวันคืนหลังวันรับ'}</p><p>ค่าเช่า {money(fee)}</p><p>เงินประกัน {money(product?.rent||0)}</p><strong>ยอดชำระ {money(fee+(product?.rent||0))}</strong><p className="text-sm mt-2">{remaining===null?'กำลังตรวจวันว่าง…':remaining?`ว่าง ${remaining} ตัว`:'ไม่ว่างในช่วงวันที่เลือก'}</p></div><button className="shop-button w-full justify-center disabled:opacity-50" disabled={busy||!days||remaining===null||remaining<1||!product?.rent}>{busy?'กำลังบันทึก…':'ยืนยันการจอง'}</button>{!product?.rent&&<p className="text-sm text-stone-500">ชุดนี้ยังไม่กำหนดราคา กรุณาติดต่อร้านก่อนจอง</p>}</form>:login:<div className="shop-panel"><CalendarDays className="mb-4 text-[#9c7741]"/><h2 className="text-xl">เลือกวันแล้วเริ่มจอง</h2><p className="text-stone-500 mt-3">ตรวจสถานะชุดในเดือนที่ต้องการ แล้วเลือกวันรับและวันคืน</p><button className="shop-button mt-6" onClick={()=>go('booking')}>จองชุดที่เลือก</button></div>}</div></>}
      {view==='payment'&&<><h1 className="shop-title">ชำระเงิน</h1>{!user?login:loadingBookings?<p>กำลังโหลดการจอง…</p>:!bookings.length?<div className="shop-panel">ยังไม่มีการจอง <button onClick={()=>go('details')} className="underline">เลือกชุดเช่า</button></div>:<div className="grid md:grid-cols-2 gap-6"><section className="shop-panel space-y-4"><label className="shop-field">เลือกการจอง<select value={bookingId} onChange={e=>setBookingId(e.target.value)}>{bookings.map(b=><option value={b.id} key={b.id}>{b.item} · {b.start} · {b.status}</option>)}</select></label>{booking&&<><h2 className="font-semibold">{booking.item}</h2><p>วันรับ {booking.start} · วันคืน {booking.end}</p><p>ค่าเช่า {money(booking.fee)}</p><p>เงินประกัน {money(booking.deposit)}</p><p className="text-xl font-semibold">ยอดชำระ {money(booking.fee+booking.deposit)}</p><p>สถานะ: {booking.paymentStatus} · {booking.status}</p>{!booking.online&&<p className="text-sm text-stone-500">รายการเช่าหน้าร้าน กรุณาชำระกับร้านและให้พนักงานยืนยันรับชำระ</p>}{booking.rewardUsed&&<p className="text-sm text-rose-700">ใช้สิทธิ์เช่าฟรี 10 แต้ม · เงินประกันตามอัตราปกติ</p>}{booking.paymentSlip&&<a href={booking.paymentSlip} target="_blank" rel="noreferrer" className="underline">ดูหลักฐานที่ส่ง</a>}{booking.online&&!['ยกเลิก','คืนแล้ว'].includes(booking.status)&&booking.paymentStatus!=='ชำระแล้ว'&&<label className="shop-field">แนบหลักฐานชำระเงิน<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{if(e.target.files?.[0])sendFile(e.target.files[0],'slip');e.target.value='';}}/><span className="text-xs text-stone-500">JPG / PNG / WebP ไม่เกิน 5 MB · ร้านจะตรวจสอบก่อนยืนยัน</span></label>}</>}</section><section className="shop-panel"><h2 className="font-semibold mb-4">ข้อมูลรับชำระของร้าน</h2>{info.account?<><p>{info.bank}</p><p>ชื่อบัญชี {info.accountName}</p><p className="text-xl mt-3 font-mono">{info.account}</p></>:<p className="text-stone-500">กรุณาติดต่อร้านเพื่อรับข้อมูลชำระเงิน</p>}<button className="shop-button secondary mt-6" onClick={()=>go('contact')}>ติดต่อร้าน</button></section></div>}</>}
      {view==='bookings'&&<><h1 className="shop-title">ข้อมูลการจอง+สะสมแต้ม</h1>{user&&<LoyaltyCard/>}{!user?login:loadingBookings?<p>กำลังโหลด…</p>:<div className="space-y-4">{!bookings.length&&<p className="shop-panel">ยังไม่มีการจองของคุณ</p>}{bookings.map(b=><article key={b.id} className="shop-panel"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold">{b.item}</h2><span className="bg-[#f5f1e8] rounded-full px-3 py-1 text-xs">{b.status}</span></div><p className="text-xs text-stone-500 mt-2 break-all">{b.id}</p><div className="grid sm:grid-cols-3 gap-3 mt-4 text-sm"><p>วันรับ {b.start}</p><p>กำหนดคืน {b.end}</p><p>{b.paymentStatus}</p></div><p className="text-sm mt-3">ค่าเช่า {money(b.fee)} · เงินประกัน {money(b.deposit)}</p><div className="flex flex-wrap gap-3 mt-4"><button className="shop-button secondary" onClick={()=>go('payment',b.code,b.id)}>ยอดและหลักฐานชำระ</button>{!b.rewardUsed&&b.fee>0&&b.fee<=350&&!b.stockReturned&&(!b.stockApplied||!b.online&&b.status==='จองแล้ว')&&b.paymentStatus!=='ชำระแล้ว'&&b.status!=='ยกเลิก'&&<button disabled={busy} className="shop-button secondary" onClick={async()=>{if(!window.confirm('ใช้ 10 แต้มเช่าฟรี ค่าเช่าไม่เกิน 350 บาท เงินประกันตามปกติ?'))return;setBusy(true);try{await json('/api/shop/loyalty/redeem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rentalId:b.id})});await loadBookings();window.dispatchEvent(new Event('loyalty-updated'));setMessage('ใช้สิทธิ์เช่าฟรีแล้ว เงินประกันตามปกติ');}catch(e){setError(e instanceof Error?e.message:'ใช้สิทธิ์ไม่สำเร็จ');}finally{setBusy(false);}}}>ใช้ 10 แต้มเช่าฟรี</button>}{b.status==='คืนแล้ว'&&<button className="shop-button secondary" onClick={()=>go('reviews',b.code,b.id)}>เขียนรีวิว</button>}{b.online&&!b.stockApplied&&!['คืนแล้ว','ยกเลิก'].includes(b.status)&&b.paymentStatus!=='ชำระแล้ว'&&<button disabled={busy} onClick={()=>cancel(b)} className="text-sm text-rose-700 underline">ยกเลิกการจอง</button>}</div></article>)}</div>}</>}
      {view==='reviews'&&<><h1 className="shop-title">รีวิวลูกค้า</h1><p className="text-stone-500 mb-7">ประสบการณ์จากลูกค้าที่ใช้บริการจริง และอนุญาตให้ร้านเผยแพร่</p><div className="grid sm:grid-cols-2 md:grid-cols-3 gap-5">{reviews.map(r=><article className="shop-panel" key={r.id}>{r.image&&<img src={r.image} alt={'ภาพที่ '+r.name+' อนุญาตให้เผยแพร่'} className="rounded-xl w-full aspect-[3/4] object-cover mb-4"/>}<p className="whitespace-pre-line">{r.text}</p><p className="text-xs mt-4 text-stone-500">{r.name}</p></article>)}</div>{!reviews.length&&<p className="shop-panel">ยังไม่มีรีวิวที่เผยแพร่</p>}{user&&bookings.some(b=>b.status==='คืนแล้ว')&&<form className="shop-panel max-w-xl mt-8 space-y-4" onSubmit={sendReview}><h2 className="font-semibold">เขียนรีวิวหลังใช้บริการ</h2><label className="shop-field">การจองที่คืนชุดแล้ว<select required value={bookingId} onChange={e=>{setBookingId(e.target.value);setReviewImage('');}}><option value="">เลือกการจอง</option>{bookings.filter(b=>b.status==='คืนแล้ว').map(b=><option key={b.id} value={b.id}>{b.item} · {b.start}</option>)}</select></label><label className="shop-field">รีวิว<textarea required maxLength={2000} value={reviewText} onChange={e=>setReviewText(e.target.value)}/></label><label className="shop-field">ภาพของคุณ (ไม่บังคับ)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!bookingId} onChange={e=>{if(e.target.files?.[0])sendFile(e.target.files[0],'review');e.target.value='';}}/></label>{reviewImage&&<img src={reviewImage} alt="ภาพรีวิวที่เลือก" className="w-24 rounded-lg"/>}<label className="flex gap-2 text-sm"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>ฉันอนุญาตให้ร้านเผยแพร่ชื่อ รีวิว และภาพที่ส่งนี้</label><button className="shop-button" disabled={busy||!consent||bookings.find(b=>b.id===bookingId)?.status!=='คืนแล้ว'}>ส่งรีวิวให้ร้านตรวจสอบ</button></form>}</>}
      {view==='contact'&&<><h1 className="shop-title">ติดต่อร้าน</h1><div className="grid md:grid-cols-2 gap-6"><section className="shop-panel space-y-5"><h2 className="font-serif text-xl tracking-widest">HONEY STUDIO</h2>{info.address&&<p className="flex gap-3"><MapPin size={20}/>{info.address}</p>}{info.phone&&<a className="flex gap-3 underline" href={'tel:'+info.phone.replace(/[^+\d]/g,'')}><Phone size={20}/>{info.phone}</a>}{<a target="_blank" rel="noreferrer" className="flex gap-3 underline" href="https://lin.ee/OfHxMgW"><MessageCircle size={20}/>ติดต่อเราทาง LINE</a>}{info.social&&<a href={info.social} target="_blank" rel="noreferrer" className="block underline">ช่องทางโซเชียลของร้าน</a>}{info.map&&<a href={info.map} target="_blank" rel="noreferrer" className="shop-button secondary">เปิดแผนที่ร้าน</a>}</section><section className="shop-panel"><h2 className="font-semibold mb-3">เลือกชุดก่อนเข้าร้าน</h2><p className="text-stone-500 leading-7">ดูขนาดและช่วงวันที่ว่าง จองชุดที่ต้องการ แล้วตรวจสอบการจองจากแอพได้ทุกเวลา</p><button className="shop-button mt-5" onClick={()=>go('details')}>ดูรายละเอียดชุด</button></section></div></>}
    </main><LineContact/><footer className="border-t border-stone-200 mt-12"><div className="max-w-6xl mx-auto px-5 py-8 flex flex-wrap items-center justify-between gap-5"><div><strong className="font-serif tracking-widest">HONEY STUDIO</strong><p className="text-xs text-stone-500 mt-2">ชุดเช่าสำหรับวันสำคัญของคุณ</p></div><InstallApp/><a href="/staff" className="text-xs text-stone-500 underline">สำหรับพนักงาน</a></div></footer>
  </div>;
}
