import assert from 'node:assert/strict';
import QRCode from 'qrcode';
import {qrLabelPdf,qrLabelsPdf} from '../lib/qr-label-pdf';
const qr=QRCode.create('https://honey-studio-opal.vercel.app/p/HS-4282',{errorCorrectionLevel:'M'});
for(const id of ['HS-4282','HS-SKY-008','HS-(test)\\008']){
  const pdf=new TextDecoder().decode(qrLabelPdf(id,qr.modules));
  assert.ok(pdf.includes('/Count 1'));
  assert.ok(pdf.includes('/MediaBox [0 0 141.7323 198.4252]'));
  assert.equal((pdf.match(/\/Type \/Page\b/g)||[]).length,1);
  const startxref=Number(pdf.match(/startxref\n(\d+)/)![1]);
  assert.equal(pdf.slice(startxref,startxref+4),'xref');
  const offsets=[...pdf.matchAll(/(\d{10}) 00000 n/g)].map(match=>Number(match[1]));
  offsets.forEach((offset,index)=>assert.ok(pdf.slice(offset).startsWith(`${index+1} 0 obj`)));
  const stream=pdf.match(/\/Length (\d+) >>\nstream\n([\s\S]*?)endstream/)!;
  assert.equal(Number(stream[1]),stream[2].length);
  assert.equal((pdf.match(/ re f/g)||[]).length,Array.from({length:qr.modules.size},(_,row)=>Array.from({length:qr.modules.size},(_,col)=>Number(qr.modules.get(row,col))).reduce((a,b)=>a+b,0)).reduce((a,b)=>a+b,0));
  assert.ok(!pdf.includes('/staff'));
  assert.equal((pdf.match(/ Tj/g)||[]).length,1,'Only the dress code is printed as text');
  assert.ok(!pdf.includes('https://'));
  assert.ok(!pdf.includes('/CreationDate'));
}
const batch=new TextDecoder().decode(qrLabelsPdf(['HS-001','HS-002','HS-003'].map(id=>({id,modules:qr.modules}))));
assert.ok(batch.includes('/Count 3'));
assert.equal((batch.match(/\/Type \/Page\b/g)||[]).length,3);
assert.ok(batch.includes('/Kids [3 0 R 6 0 R 8 0 R]'));
for(const id of ['HS-001','HS-002','HS-003'])assert.ok(batch.includes(`(${id}) Tj`));
const refs=[...batch.matchAll(/\/Contents (\d+) 0 R/g)].map(match=>Number(match[1]));
assert.deepEqual(refs,[5,7,9]);
for(const match of batch.matchAll(/\/Length (\d+) >>\nstream\n([\s\S]*?)endstream/g))assert.equal(Number(match[1]),match[2].length);
const offsets=[...batch.matchAll(/(\d{10}) 00000 n/g)].map(match=>Number(match[1]));
offsets.forEach((offset,index)=>assert.ok(batch.slice(offset).startsWith(`${index+1} 0 obj`)));
assert.throws(()=>qrLabelsPdf([]));
assert.throws(()=>qrLabelsPdf(Array.from({length:501},()=>({id:'HS-001',modules:qr.modules}))));
console.log('PASS: single and batch 50x70mm PDFs, QR and code only, page order, byte offsets and stream lengths');
